### ISSUE TITLE
Tracking build metrics

### ISSUE THREAD

**Issue by matthiasbeyer** [science-computing/butido#12]
The database does not yet contain build metrics, but tracking such metrics could improve the usability quite a bit.

E.G:

* Tracking the time a specific package build took could be used to forecast future build times (e.g. of package updates even)
* Success of builds is not yet tracked in the DB, but could significantly reduce load when searching for builds

**Comment by christophprokop** [comment]
1. success of builds is in db and shown in output of `butido db jobs` 
2. build duration is tracked in last line of log files
all is fine here :)
