### ISSUE TITLE
subcommand "list" for butido release --from <STORE> list

### ISSUE THREAD

**Issue by christophprokop** [science-computing/butido#143]
butido release only support adding and removing packages but the frontend currently does not yet provide a means to list all current releases for a store (or for all stores? ;) )

**Comment by primeos-work** [comment]
I've added a "list" subcommand in #322 that reuses the "butido db releases" implementation:
```
$ butido release list -h
List releases

Usage: butido release list [OPTIONS]

Options:
      --csv                Format output as CSV
      --older-than <DATE>  List only releases older than DATE
      --newer-than <DATE>  List only releases newer than DATE
      --to <STORE>         List only releases to STORE
  -p, --package <PKG>      Only list releases for package PKG
  -h, --help               Print help (see more with '--help')
```

The existing implementation uses `--to` instead of `--from` but we could also, e.g., switch to `--store` and support both `--from` and `--to` as (hidden) aliases.
