### ISSUE TITLE
butido tree-of does not distinguish between build and runtime dependencies

### ISSUE THREAD

**Issue by christophprokop** [science-computing/butido#177]
```
$ egrep 'runtime|build' ffmpeg/6.0/pkg.toml
build   = ["yasm =1.3.0"]
runtime = ["libsdl2 =2.24.1", "openh264 =2.2.0", "libzlib =1.2.12"]

ffmpeg 6.0
├─ libzlib 1.2.12
├─ openh264 2.2.0
├─ libsdl2 2.24.1
└─ yasm 1.3.0
```

This way the output does not show which depencies are only needed for the build (here: yasm).

**Comment by primeos-work** [comment]
We should probably first create a mockup of the output.

An interesting case would be a dependency that is both a build and runtime dependency (not sure if we have that case in our packages repo but that is theoretically possible and I already know this case from Nixpkgs).

Could be something as simple as marking build/compile-time dependencies with a star:
```
ffmpeg 6.0
├─ libzlib 1.2.12
├─ openh264 2.2.0
├─ libsdl2 2.24.1
└─ *yasm 1.3.0
```

Or something more advanced like:
```
ffmpeg 6.0
├─ [-r] libzlib 1.2.12
├─ [-r] openh264 2.2.0
├─ [-r] libsdl2 2.24.1
└─ [b-] yasm 1.3.0
```

Any ideas/whishes?
Looking at some other tools / package managers might also be a good idea.

**Comment by christophprokop** [comment]
"more advanced" with `[-r]` or `[b-]` is not needed here. In most cases we have more runtime dependencies and few (or even no) build dependencies (like in this case yasm)
So the first option with the prefixed asterisk (`*`) is fine.
