### ISSUE TITLE
option/flag to filter output of "butido db jobs" on used image

### ISSUE THREAD

**Issue by christophprokop** [science-computing/butido#183]
Since #178 works very well (thx again! <3) it would be helpful to be able to filter the output of `butido db jobs` on the used image, preferably using the shortname.
maybe the same flag as in `butido build`:

e.g.
`butido db jobs -p tmux -I rh7`
`butido db jobs -p tmux --image rh7`

**Comment by primeos-work** [comment]
Sounds good but I'd suggest that we implement an abstraction and use that everywhere where the `-I`/`--images` option is available (for consistency and to make this more useful).

And I need to check if we need some additional verification of the `images` setting.
(I also wonder if we should enforce that the full image name contains a colon (`:`) and forbid it in the short name to easily distinguish between the two in the code but I'm not sure on that yet.)

**Comment by christophprokop** [comment]
Thumbs up for consistency of flags between subcommands :)

To never use colon (`:`) in shortnames is perfectly fine, in full images names it has always been the same (`local:`) so this is already a convention we have and that we now could make mandatory / enforce.
