### ISSUE TITLE
Specifying dependencies as KV-pairs?

### ISSUE THREAD

**Issue by matthiasbeyer** [science-computing/butido#21]
Right now, dependencies are specified as a list of strings, where the strings are then parsed.

It might be beneficial, though, to specify them as key-value pairs, so they can be easily overwritten.

**Comment by christophprokop** [comment]
not neeed at the moment

**Comment by primeos-work** [comment]
Looks like this issue was regarding the system dependencies for which we currently use the `SYS_BUILD_DEPENDS_*` environment variables. Related issues: #184 and #185.
