### ISSUE TITLE
error on dependency names startint with numerals

### ISSUE THREAD

**Issue by christophprokop** [science-computing/butido#356]
butido seems not to be able to handle dependencies starting with numerals:

```
Error: build command failed
Caused by:
package name and package version constraint: '7z =23.01'
```

building the package directly works fine though

**Comment by primeos-work** [comment]
Nice catch, thanks! :)
#358 should fix it - at least it passed my testing where I could reproduce it with the following error message (the "Could not parse into" probably went missing when you copied the output):
```
Error: build command failed

Caused by:
    Could not parse into package name and package version constraint: '7z =1.8.0'
```
