### ISSUE TITLE
butido tree-of --dot

### ISSUE THREAD

**Issue by christophprokop** [science-computing/butido#378]
butido tree-of currently only presents a tree view of the DAG with lots of duplicates

butido tree-of --dot
    to get a better overview over builds with a lot of deps we would be happy to have a graphical view (like dot files)

**Comment by ammernico** [comment]
Is there some prefered method for showing this dot graph?

Maybe the dot format which is used bu graphviz?
("https://en.wikipedia.org/wiki/DOT_(graph_description_language)")
("https://gitlab.com/graphviz/graphviz")
("https://graphviz.org/Gallery/directed/")

There would also be a crate available for this: ("https://crates.io/crates/graphviz-rust")

**Comment by primeos-work** [comment]
Yes, the issue description is a bit brief but `--dot` refers to the format so the intention was to output the graph using the text-based DOT format/language (https://en.wikipedia.org/wiki/DOT_(graph_description_language)).

It doesn't necessarily have to be DOT though but it makes sense as it's a common format.
