### ISSUE TITLE
new column "distro" in butido db jobs output

### ISSUE THREAD

**Issue by christophprokop** [science-computing/butido#48]
$ butido db jobs -L 1
│ Submit                               │ Job                                  │ Time                │ Endpoint │ Success │ Package           │ Version  │
│ 40c0be74-0b77-457c-86a0-a1cd4f4cd1a9 │ ed855e87-0537-4b34-a45e-a7725e8b8e26 │ 2022-11-14 10:34:46 │ host1 │ yes     │ demo-app │ 1.2.3│

butido db jobs does not list linux distro short name (e.g. "rh8", "sles15", ...)
location for the new column: far right (after "package" and "version")

**Comment by matthiasbeyer** [comment]
Related to #49
