### ISSUE TITLE
Prepend  "$app-$version-$distroshortname-" to logfile  names

### ISSUE THREAD

**Issue by christophprokop** [science-computing/butido#50]
butido build --help
     [...]
   -L, --write-log
            With this flag set, butido does not only write the build logs to database, but also to
            the configured
            log directory.

            The log of a build is written to `<log_dir>/<build id>.log`.
          [...]
---------

logs are currently named $UUID.log
would be helpful to name them $UUID-$app-$version-$distroshortname.log

**Comment by primeos-work** [comment]
We decided to prepend the package name and version to the logfile name instead of appending for the reasons explained in #97.
