### ISSUE TITLE
revert load balancer feature

### ISSUE THREAD

**Issue by christophprokop** [science-computing/butido#51]
load balancer does not balance within one submit
e.g. submit target with 300 dependencies -> almost all jobs run on the same endpoint / build host
next submit -> almost all jobs run on the next endpoint / build host

simple improvement of the current situation:
round-robin the jobs:
e.g. current job number modulo number of endpoints

**Comment by christophprokop** [comment]
revert this, then try with a target with a lot of dependencies (you know which one i am thinking of ;) )
https://github.com/science-computing/butido/commit/63566cccba0c2c42af2e38d7ec0a922a60cf128d

**Comment by christophprokop** [comment]
i tested with 63566cc reverted for the last few weeks and all build hosts are evenly considered for jobs
if @matthiasbeyer is has no problems with it, i would suggest to revert 63566cc in master

**Comment by matthiasbeyer** [comment]
Why would I have a problem with you reverting patches in your software? :laughing:

**Comment by christophprokop** [comment]
> Why would I have a problem with you reverting patches in your software? 😆

you initially wrote it, that's why your opinion matters to me :)
here: wanted to ask you if i did not realize if reverting this part is enough or if it's fine to take it out just like that

**Comment by matthiasbeyer** [comment]
> you initially wrote it, that's why your opinion matters to me :)

Yes but I am not responsible anymore. :laughing:

If you verified that the feature works with that patch reverted, that's enough IMO.

**Comment by christophprokop** [comment]
ok cool ;)
