### ISSUE TITLE
reduce size of progress bar

### ISSUE THREAD

**Issue by christophprokop** [science-computing/butido#53]
the progress bar during builds does use up more space than needed
half of it would be enough

**Comment by matthiasbeyer** [comment]
The fix here would be to make the progress bar size dependent on the terminal width.

**Comment by christophprokop** [comment]
The progress bar is nice but 10 characters wide for 100% is enough in all cases.
But a setting option in ~/.config/butido/config.toml to make it even shorter (5 characters wide) would be nice to have :)

oh wait!
i just found this: (never noticed before, sorry!)
https://github.com/science-computing/butido/blob/master/config.toml#L15
maybe the user can just configure for himself already?

**Comment by christophprokop** [comment]
yep, it works just fine as it is
just replaced the default (40) and it works as desired.
sorry for the noise :)

**Comment by matthiasbeyer** [comment]
Ah, yes.

I think I did a good job... Feel free to close!

**Comment by matthiasbeyer** [comment]
No need to apologize to me for noise on _your_ repository!

**Comment by christophprokop** [comment]
XD
