### ISSUE TITLE
Replace "log" with "tracing"

### ISSUE THREAD

**Issue by matthiasbeyer** [science-computing/butido#55]
This would be a really good idea, because right now butido uses `log`, but in general the `tracing` ecosystem should be used for async code.

That change is rather simple IMO (but one learns to navigate the codebase rather well, as potentially every `async` function and every `await` should be annotated). May be perfect for someone learning the project codebase.

**Comment by primeos-work** [comment]
> as potentially every async function and every await should be annotated

@matthiasbeyer just to be sure: You refer to the `#[instrument]` attribute macro and the `Future::instrument` combinator here, right? (I only took a quick look at https://github.com/tokio-rs/tracing#in-asynchronous-code so far.)

**Comment by matthiasbeyer** [comment]
Yes. Make sure to not include everything in the instrumentation (there's several variants of `skip` attributes for the `instrument` annotation). Only where it makes sense.
