### ISSUE TITLE
"error on other task" on many builds - which one?

### ISSUE THREAD

**Issue by christophprokop** [science-computing/butido#57]
error on other task stops all jobs, but which job triggered it?
with some patience and scrolling you can find out yourself, but explicitly name the package which had the error in the last line (small summary) would be nice

or just print it in red, so scrolling and finding it is no hassle

**Comment by matthiasbeyer** [comment]
I _think_ this is more a problem of the way logging is currently implemented. Solving #55 might be a good idea.

**Comment by christophprokop** [comment]
for the moment: colored output for "error on other task" would be enough

**Comment by christophprokop** [comment]
output much better readable since 71b1921
