### ISSUE TITLE
option to manually override "reusing artifact" mechanism

### ISSUE THREAD

**Issue by christophprokop** [science-computing/butido#98]
goal:
quicker iterations while putting together a new build script 

current situation:
if the top level pkg.toml was modified no reuse is possible for the next submit
this can be pretty annoying and time consuming if one or more dependencies take a long time to build

feature request:
if you know what you are doing (TM) you should be able to manually force a reuse of artifacts in a certain staging directory

**Comment by matthiasbeyer** [comment]
Why is it annoying that the build takes long?

Anything that happens after a successful build should be happen automatically anyways, so I'd suggest to rather add more functionality to auto-release after a build finished than adding loopholes that one can (and will!) use to screw up things.

**Comment by christophprokop** [comment]
the "reuse artifact" mechanism seems to work fine (no more unexpected rebuilds) (just like #145)
